[global]

author=["konami-fpga"]

[parse]

sourcefile=[ "asterix.cpp" ]
skip = { bootlegs=true }

rename = [
    { setname="asterix",    name="Asterix (FF ver EAD)" },
    { setname="asterixaad", name="Asterix (FF ver AAD)" },
    { setname="asterixeaa", name="Asterix (FF ver EAA)" },
    { setname="asterixeac", name="Asterix (FF ver EAC)" },
    { setname="asterixj",   name="Asterix (FF ver JAD)" },
]

[buttons]
names = [
    { machine="asterix", names="Punch,Jump" },
]

[header]
info="Offsets for each ROM region."

offset = { bits=12, reverse=true, regions=["maincpu","audiocpu","k056832","obj"] }
frames = [ { width=8 }, ]

[ROM]
regions = [
    { name="maincpu",  width=16, reverse=true },
    { name="audiocpu" },
    { name="k053260",  rename="pcm" },
    { name="k056832",  width=32 },
    { name="k053244",  width=32, rename="obj" },
    { name="eeprom",   skip=true }
]

order=["maincpu","audiocpu","pcm","k056832","obj"]

nvram={ Defaults=[
    { setname="asterix", data="""\
    00 28 ff d7 90 68 65 61 63 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 02 04 00 01 01 00 01 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00"""},
]}
